/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SimpleCircularProgress {
        "hideLabel": boolean;
        "label": string;
        "labelFontSize": string;
        "progressColor": string;
        "progressPercentage": string;
        "progressStrokeColor": string;
    }
}
declare global {
    interface HTMLSimpleCircularProgressElement extends Components.SimpleCircularProgress, HTMLStencilElement {
    }
    var HTMLSimpleCircularProgressElement: {
        prototype: HTMLSimpleCircularProgressElement;
        new (): HTMLSimpleCircularProgressElement;
    };
    interface HTMLElementTagNameMap {
        "simple-circular-progress": HTMLSimpleCircularProgressElement;
    }
}
declare namespace LocalJSX {
    interface SimpleCircularProgress {
        "hideLabel"?: boolean;
        "label"?: string;
        "labelFontSize"?: string;
        "progressColor"?: string;
        "progressPercentage"?: string;
        "progressStrokeColor"?: string;
    }
    interface IntrinsicElements {
        "simple-circular-progress": SimpleCircularProgress;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "simple-circular-progress": LocalJSX.SimpleCircularProgress & JSXBase.HTMLAttributes<HTMLSimpleCircularProgressElement>;
        }
    }
}
